In [1]:
import numpy as np

#### Creating numpy arrays from python lists

In [2]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8]

In [3]:
my_arr = np.array(my_list)

In [4]:
my_arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
arr1 = my_arr.reshape(2,4)

#### Finding max value of array

In [29]:
arr1.max()

8

#### Finding index of max falue

In [34]:
arr1.argmax()

7

#### Choosing a submatrix

In [44]:
big = np.arange(100).reshape(10,10)
big

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

Choose 22 - 45 matrix

In [48]:
sub = big[2:5, 2:6]
sub

array([[22, 23, 24, 25],
       [32, 33, 34, 35],
       [42, 43, 44, 45]])

#### Range evenly divided on given number of points
Generate range 1 to 10 divided on 20 numbers

In [53]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])